name: j1_theme
description: "A common theme class and Flutter builders for the J1 apps."
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dart_mappable: ^4.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.2

  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  mocktail: ^1.0.4
