name: flutter tests

on:
  push:
    branches: [develop, release]
  pull_request:
    branches: [develop, release]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: check version
        run: flutter --version

      - name: update dependencies
        run: flutter pub get

      - name: analyze
        run: flutter analyze

      - name: test
        run: flutter test --coverage

      - name: upload to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}